### ISSUE TITLE
Сompatibility with another extension

### ISSUE THREAD

**Issue by D0n-A** [Haoming02/sd-webui-tabs-extension#19]
Hello! I won't describe the problem again, it has already been described [here](https://github.com/Inzaniak/sd-webui-ranbooru/issues/36).  Is it possible to fix this from your side or should the author of that extension fix it directly? Thanks!

**Comment by Haoming02** [comment]
From beirfly looking through the code, this can probably be fixed by removing this [line](https://github.com/Inzaniak/sd-webui-ranbooru/blob/main/scripts/ranbooru.py#L585) and this [line](https://github.com/Inzaniak/sd-webui-ranbooru/blob/main/scripts/ranbooru.py#L641), therefore the `InputAccordion` is at the top level within the Extension, instead of being nested 1 layer deep.

I can probably support it. But this will be low priority for me.

**Comment by Haoming02** [comment]
Does it work correctly after you made the changes?

If so, I'll close this Issue then.

**Comment by D0n-A** [comment]
Yes, it is correct, I hope the author will make the necessary changes. Thanks!
